language: node_js
node_js:
  - "10"

install:
  - yarn
script:
  - npm run build && npm run test:coverage

deploy:
  provider: script
  script: "cp .npmrc.template $HOME/.npmrc && npm publish"
  skip_cleanup: true
  on:
    tags: true
    branch: master
    condition: ${TRAVIS_TAG} =~ ^v[0-9]+\.[0-9]+\.[0-9]+.*$
