language: node_js
node_js:
  - "10"

install:
  - yarn
script:
  - npm run build && npm run test:coverage

deploy:
  provider: npm
  email: EMAIL
  api_key: NPM_TOKEN
  skip_cleanup: true
  on:
    branch: master
    tags: true
    condition: ${TRAVIS_TAG} =~ ^v[0-9]+\.[0-9]+\.[0-9]+.*$
